### ISSUE TITLE
Jenkins 2.357 breaks usage. Returns null passwords

### ISSUE THREAD

**Issue by MiguelArroja** [jenkinsci/keeper-secrets-manager-plugin#8]
### Jenkins and plugins versions report

After Jenkins update to 2.357, the returned passwords are always null.

### What Operating System are you using (both controller, and any agents involved in the problem)?

linux 20.0.4

### Reproduction steps

Update Jenkins to 2.357

### Expected Results

Get the actual password from keeper

### Actual Results

Null value

**Comment by jsupun** [comment]
I'll take a look to see what is going on.

**Comment by jsupun** [comment]
The new release 1.0-71.v4e77ee1673fd should fix the problem.

Jenkins looks like they updated Bouncy Castle to a version that was not compatible with the KSM SDK version being used. I updated my test Jenkins to 2.357 and had problems adding a new one time access token. After switching to the latest KSM SDK, I had no problems. I was able to run build and pipeline tests.

**Comment by MiguelArroja** [comment]
Thanks! Will try it it and comeback to you
